version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: tinygithub-mysql
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 3s
      retries: 10

  tinygithub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinygithub
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_IP=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - STORAGE=${STORAGE}
      - SERVER_IP=${SERVER_IP}
      - LOG_LEVEL=debug
    healthcheck:
      test: [ "CMD", "curl", "localhost:8083" ]
      interval: 5s
      timeout: 3s
      retries: 5
  nginx:
    image: nginx:latest
    container_name: tinygithub-nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      tinygithub:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/tinygithub-frontend/dist:/usr/share/nginx/html
volumes:
  db:
    driver: local