version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  tinygithub:
    image: adlternative/tinygithub:latest
    restart: always
    environment:
      - DB_IP=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - STORAGE=${STORAGE}
      - SERVER_IP=${SERVER_IP}
    depends_on:
      - db
    ports:
      - "8083:8083"
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - tinygithub
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/tinygithub-frontend/dist:/usr/share/nginx/html
volumes:
  db:
    driver: local